### ISSUE TITLE
Way to Convert PDF to LaTeX

### ISSUE THREAD

**Issue by sirinath** [davidar/TeX.js#13]
I am looking for a means to convert PDF to LaTeX. E.g. http://dharmafarer.org/wordpress/wp-content/uploads/2010/02/31.1-Pahana-S-s36.3-piya.pdf

Wondering is such functionality can be added to https://davidar.io/TeX.js/

**Comment by davidar** [comment]
@sirinath This is an interesting problem, but is outside the scope of this project. You may be interested in reading https://known.phyks.me/2016/comparison-of-tools-to-fetch-references-for-scientific-papers
