### ISSUE TITLE
Reference tooltips/reveal

### ISSUE THREAD

**Issue by davidar** [davidar/TeX.js#4]
- https://www.mediawiki.org/wiki/Reference_Tooltips
- https://www.mediawiki.org/wiki/Mobile_design/Reference_reveal

**Comment by michal-h21** [comment]
I've done something similar for tex4ht: 
- https://github.com/michal-h21/tex4ht-enhanced-web
- and some explanation of the process: http://tex.stackexchange.com/a/239944/2891

**Comment by davidar** [comment]
@michal-h21 Thanks, I'll have a look
