### ISSUE TITLE
Intra-document anchors

### ISSUE THREAD

**Issue by davidar** [davidar/TeX.js#7]
We should automatically generate (HTML) anchors to facilitate linking to specific sections and paragraphs of a piece of text.
- https://github.com/hypothesis/h/wiki/Robust-anchors
- https://github.com/hypothesis/h/wiki/Linking-to-an-annotation

**Comment by rht** [comment]
Turns out there is a term for this (in the case where the sections/paragraphs can be standalone) http://nanopub.org/wordpress/?page_id=65.

**Comment by rht** [comment]
This is like the [internet of code](http://www.haskellforall.com/2015/05/the-internet-of-code.html) but for scientific hypothesis/proposition/fact.

**Comment by davidar** [comment]
@rht Hmm, interesting. That also kind of ties into my idea of extracting definitions from papers. I wonder which parts of a paper could be generally considered "standalone" as-is, and how much could be converted into a standalone form after some analysis? Also see http://deepdive.stanford.edu/
